name: Pass/Fail Check

on:
  push:
    branches: [ master ]
    paths:
      - 'verify/**/*'
  pull_request:
    branches: [ master ]
    paths:
      - 'verify/**/*'


jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for control file
      id: file_check
      run: |
        if [ -f "verify/FAIL" ]; then
          echo "❌ Control file 'FAIL' found - workflow will FAIL"
          echo "result=fail" >> $GITHUB_OUTPUT
          exit 1
        else
          echo "✅ No control file found - workflow will PASS by default"
        fi
